openssl: small fixes

diff --git a/trunk/libs/libssl/openssl-1.0.2/test/testssl b/trunk/libs/libssl/openssl-1.0.2/test/testssl
--- a/trunk/libs/libssl/openssl-1.0.2/test/testssl
+++ b/trunk/libs/libssl/openssl-1.0.2/test/testssl
@@ -175,16 +175,16 @@ for protocol in TLSv1.2 SSLv3; do
     if [ $protocol = "SSLv3" ] && ../util/shlib_wrap.sh ../apps/openssl no-ssl3; then
       echo "skipping weak DH test for disabled protocol"
     else
-      if [ $protocol = "SSLv3" ] ; then
-        $ssltest -cipher EDH -dhe512 -ssl3
-      else
-        $ssltest -cipher EDH -dhe512
-      fi
-      if [ $? -eq 0 ]; then
-        echo "FAIL: connection with weak DH succeeded"
-        exit 1
-      fi
+    if [ $protocol = "SSLv3" ] ; then
+      $ssltest -cipher EDH -dhe512 -ssl3
+    else
+      $ssltest -cipher EDH -dhe512
     fi
+    if [ $? -eq 0 ]; then
+      echo "FAIL: connection with weak DH succeeded"
+      exit 1
+    fi
+  fi
   fi
   if ../util/shlib_wrap.sh ../apps/openssl no-ec; then
     echo "skipping RSA+ECDHE tests"
